Added a reverse string extension function
AbhishekDoshi26/super_extensions pull request #23
Opened 2023-03-26 10:40 UTC by logickoder

## Description

## Basic Checklist

- [ ] ✨ Ran `dartdoc`
- [ ] 🛠️ Added proper documentation
- [x] ❌ No warnings or errors in the code
- [x] ✅ If added a new extension, added in Readme and example too
- [x] 🧪 If added a new extension, written proper test cases for it

## Type of Change

- [x] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

2023-03-26 11:20 UTC, AbhishekDoshi26 requested changes

2023-03-26 11:20 UTC, AbhishekDoshi26 commented on lib/src/string_extensions.dart
> +  }
Use arrow operator

2023-03-26 11:43 UTC, logickoder commented on lib/src/string_extensions.dart
> +  }
Done

2023-04-05 18:24 UTC, AbhishekDoshi26 approved these changes
Sorry for the delay. LGTM! Thanks!

2023-04-05 18:24 UTC, merged