feat(extension): add `colorscheme` extension on buildcontext
AbhishekDoshi26/super_extensions pull request #33
Opened 2024-01-02 20:39 UTC by baimamboukar

## Description

## Basic Checklist

- [ ] ✨ Ran `dartdoc`
- [ ] 🛠️ Added proper documentation
- [x] ❌ No warnings or errors in the code
- [x] ✅ If added a new extension, added in Readme and example too
- [ ] 🧪 If added a new extension, written proper test cases for it

## Type of Change

- [x] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

2024-01-02 20:51 UTC, AbhishekDoshi26 requested changes
See comment.

Also, please add test for the same and add example too.

Also check the codecov pipeline which is failing.

Apart from that, in my opinion, instead of having a colorScheme extension, won't it be beneficial to have Theme extension so that we can access `context.theme`. The reason is, this way, we won't need to create extensions for individual methods/getters of Theme class.

WDYT?

2024-01-02 20:51 UTC, AbhishekDoshi26 commented on .vscode/settings.json
> +            "source.organizeImports": "explicit",
Please revert this

2024-01-03 01:37 UTC, baimamboukar commented
Hey @AbhishekDoshi26 👋

Thanks for your prompt review. I took in consideration your observations and refined things you pointed out. please check here https://github.com/AbhishekDoshi26/super_extensions/pull/34

2024-01-03 01:37 UTC, baimamboukar commented
Closing this 🥲

2024-01-03 01:37 UTC, closed without merging