[ADD]: copy to clipboard extension method on String
AbhishekDoshi26/super_extensions pull request #5
Opened 2023-02-25 00:24 UTC by baimamboukar

Added copy to clipboard extension method on String

2023-02-25 17:04 UTC, AbhishekDoshi26 requested changes

2023-02-25 17:04 UTC, AbhishekDoshi26 commented on lib/src/super_extensions_base.dart
> +  /// );
Alignment should be proper.

2023-02-25 17:04 UTC, AbhishekDoshi26 commented on lib/src/super_extensions_base.dart
> +  }
Use arrow operator.

2023-02-26 11:37 UTC, AbhishekDoshi26 commented on lib/src/super_extensions_base.dart
> +  }
@baimamboukar

2023-02-26 11:59 UTC, baimamboukar commented on lib/src/super_extensions_base.dart
> +  /// );
Okay! noted

2023-02-26 12:00 UTC, baimamboukar commented on lib/src/super_extensions_base.dart
> +  }
Alright Sir! Doing it now.... 👍🏾

2023-02-26 12:04 UTC, baimamboukar commented
Hello sir @AbhishekDoshi26 ! The requested changes have been added ❇️✅

2023-02-26 12:11 UTC, AbhishekDoshi26 approved these changes

2023-02-26 12:12 UTC, AbhishekDoshi26 commented
Perfect. @baimamboukar waiting for the github actions to complete. Nice work 🚀

2023-02-26 12:13 UTC, merged